//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int idClient { get; set; }
        public string name { get; set; }
        public string cpf { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    }
}
